name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git remote add space https://USER:$HF_TOKEN@huggingface.co/spaces/eytchh/centering-mvp-1.0
          git push space main --force
